//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AritySystems.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierCartoon
    {
        public int Id { get; set; }
        public Nullable<int> SupplierAssignedMapId { get; set; }
        public Nullable<decimal> PcsPerCartoon { get; set; }
        public Nullable<int> TotalCartoons { get; set; }
        public Nullable<decimal> NetWeight { get; set; }
        public Nullable<decimal> TotalNetWeight { get; set; }
        public Nullable<decimal> GrossWeight { get; set; }
        public Nullable<decimal> TotalGrossWeight { get; set; }
        public Nullable<decimal> CartoonSize { get; set; }
        public Nullable<decimal> CartoonBM { get; set; }
        public string CartoonNumber { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
