//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AritySystems.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier_Assigned_OrderLineItem
    {
        public int Id { get; set; }
        public Nullable<int> SupplierId { get; set; }
        public Nullable<int> OrderSupplierMapId { get; set; }
        public string Status { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual OrderLineItem_Supplier_Mapping OrderLineItem_Supplier_Mapping { get; set; }
        public virtual User User { get; set; }
    }
}
